#! /usr/bin/env perl

#===============================================================================
#         FILE: ||+filename+||
#
#  DESCRIPTION: ||+synopsis to include usage+||

#       AUTHOR: ||+Robert Hicks <sigzero@gmail.com>+||
# ORGANIZATION: ||+????+||
#      PROJECT: ||+????+||
#      CREATED: ||+YYYY-MM-DD+||
#      VERSION: ||+0.0.1+||
#===============================================================================
use strict;
use warnings;
use Carp;
||++||
